### ISSUE TITLE
Change ed25519 key for -b 16384

### ISSUE THREAD

**Issue by NatoBoram** [kirkmicz/Cheat-Sheet#1]
Hello! I stumbled upon [this](https://github.com/kirkmicz/Cheat-Sheet/blob/master/Linux%20%26%20Unix/Create%20ed25519%20key.md) from Google while searching for the largest possible ed25519 key.

I'd like to recommend changing your key size to this size : 

```bash
ssh-keygen -t ed25519 -b 16384
```

Nothing important really, since the lower sizes are already secure, but I thought it could be useful.

**Comment by kirkmicz** [comment]
Hey thanks for that
